const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Hyderabad `,
  },
  {
    id: 2,
    title: "diner double",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place,  Bangolore `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Pune`,
  },
  {
    id: 4,
    title: "country delight",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place,  Mumbai `,
  },
  {
    id: 5,
    title: "egg attack",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Chennai`,
  },
  {
    id: 6,
    title: "oreo dream",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Vizag`,
  },
  {
    id: 7,
    title: "bacon overflow",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Bhihar`,
  },
  {
    id: 8,
    title: "american classic",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place ,  Indore `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Cakes,Pastry,Pastas connaught place , Noida`,
  },
];
export default menu;
